export const breeds = [
  "All",
  "Alaskan Malamute",
  "American Bulldog",
  "American Cocker Spaniel",
  "American Eskimo Dog",
  "American Foxhound",
  "American Hairless Terrier",
  "American Pit Bull Terrier",
  "American Staffordshire Terrier",
  "Australian Shepherd",
  "Basset Hound",
  "Beagle",
  "Belgian Shepherd Dog (Malinois)",
  "Bernese Mountain Dog",
  "Bloodhound",
  "Border Collie",
  "Border Terrier",
  "Boxer",
  "Bull Terrier",
  "Bulldog",
  "Chow Chow",
  "Dachshund",
  "Dalmatian",
  "French Bulldog",
  "German Shepherd",
  "Giant Schnauzer",
  "Golden Retriever",
  "Great Dane",
  "Greyhound",
  "Havanese",
  "Husky",
  "Irish Wolfhound",
  "Italian Greyhound",
  "Jack Russell Terrier",
  "Kelpie",
  "King Charles Spaniel",
  "Labrador Retriever",
  "Maltese",
  "Pomeranian",
  "Poodle",
  "Portuguese Water Dog",
  "Pug",
  "Rhodesian Ridgeback",
  "Rottweiler",
  "Russell Terrier",
  "Shar Pei",
  "Shiba Inu",
  "Shih Tzu",
  "St. Bernard",
  "Staffordshire Bull Terrier",
  "Weimaraner",
  "Whippet"
]
